# JLINK
CONFIG_SEGGER_DEBUGMON=y
CONFIG_CORTEX_M_DEBUG_MONITOR_HOOK=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y

CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
# CONFIG_UART_ASYNC_API=y
CONFIG_NET_BUF=y
CONFIG_RING_BUFFER=y

# Logging
CONFIG_LOG=y
#CONFIG_LOG_MODE_IMMEDIATE=n
#CONFIG_LOG_MODE_DEFERRED=y
#CONFIG_LOG_MODE_MINIMAL=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Dect Phy modem
CONFIG_NRF_MODEM_LIB=y
CONFIG_MODEM_ANTENNA=n
CONFIG_NRF_MODEM_LINK_BINARY_DECT_PHY=y
CONFIG_HWINFO=y
